// DO NOT EDIT. generated by github.com/tinywasm/ormc

package config

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type Project struct {
	Id               string
	Name             string
	ClientSecretHash string
	CreatedAt        int64
}

func (m *Project) ModelName() string { return "project" }

func (m *Project) Schema() []model.Field { return ProjectModel.Fields }

func (m *Project) Pointers() []any { return []any{&m.Id, &m.Name, &m.ClientSecretHash, &m.CreatedAt} }

func (m *Project) IsNil() bool { return m == nil }

func (m *Project) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("name", m.Name)
	w.String("client_secret_hash", m.ClientSecretHash)
	w.Int("created_at", m.CreatedAt)
}

func (m *Project) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
	if v, ok := r.String("client_secret_hash"); ok {
		m.ClientSecretHash = v
	}
	if v, ok := r.Int("created_at"); ok {
		m.CreatedAt = v
	}
}

type ProjectList []*Project

func (s *ProjectList) Schema() []model.Field            { return nil }
func (s *ProjectList) Pointers() []any                  { return nil }
func (s *ProjectList) Len() int                         { return len(*s) }
func (s *ProjectList) At(i int) model.Fielder           { return (*s)[i] }
func (s *ProjectList) Append() model.Fielder            { v := &Project{}; *s = append(*s, v); return v }
func (s *ProjectList) IsNil() bool                      { return s == nil }
func (s *ProjectList) EncodeFields(_ model.FieldWriter) {}
func (s *ProjectList) DecodeFields(_ model.FieldReader) {}

func (m *Project) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Project_ = struct {
	Id               string
	Name             string
	ClientSecretHash string
	CreatedAt        string
}{
	Id:               "id",
	Name:             "name",
	ClientSecretHash: "client_secret_hash",
	CreatedAt:        "created_at",
}

func ReadOneProject(qb *orm.QB, model *Project) (*Project, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllProject(qb *orm.QB) (ProjectList, error) {
	var results ProjectList
	err := qb.ReadAll(
		func() model.Model { return &Project{} },
		func(m model.Model) { results = append(results, m.(*Project)) },
	)
	return results, err
}
